#===============================================================================
# LED Constants
#===============================================================================
ARDRONE_LED_ANIMATION_BLINK_GREEN_RED = 0
ARDRONE_LED_ANIMATION_BLINK_GREEN = 1
ARDRONE_LED_ANIMATION_BLINK_RED = 2
ARDRONE_LED_ANIMATION_BLINK_ORANGE = 3
ARDRONE_LED_ANIMATION_SNAKE_GREEN_RED = 4
ARDRONE_LED_ANIMATION_FIRE = 5
ARDRONE_LED_ANIMATION_STANDARD = 6
ARDRONE_LED_ANIMATION_RED = 7
ARDRONE_LED_ANIMATION_GREEN = 8
ARDRONE_LED_ANIMATION_RED_SNAKE = 9
ARDRONE_LED_ANIMATION_BLANK = 10
ARDRONE_LED_ANIMATION_RIGHT_MISSILE = 11
ARDRONE_LED_ANIMATION_LEFT_MISSILE = 12
ARDRONE_LED_ANIMATION_DOUBLE_MISSILE = 13
ARDRONE_LED_ANIMATION_FRONT_LEFT_GREEN_OTHERS_RED = 14
ARDRONE_LED_ANIMATION_FRONT_RIGHT_GREEN_OTHERS_RED = 15
ARDRONE_LED_ANIMATION_REAR_RIGHT_GREEN_OTHERS_RED = 16
ARDRONE_LED_ANIMATION_REAR_LEFT_GREEN_OTHERS_RED = 17
ARDRONE_LED_ANIMATION_LEFT_GREEN_RIGHT_RED = 18
ARDRONE_LED_ANIMATION_LEFT_RED_RIGHT_GREEN = 19
ARDRONE_LED_ANIMATION_BLINK_STANDARD = 20

#===============================================================================
# Animate Constants
#===============================================================================
ARDRONE_ANIMATION_PHI_M30_DEG = 0
ARDRONE_ANIMATION_PHI_30_DEG = 1
ARDRONE_ANIMATION_THETA_M30_DEG = 2
ARDRONE_ANIMATION_THETA_30_DEG = 3
ARDRONE_ANIMATION_THETA_20DEG_YAW_200DEG = 4
ARDRONE_ANIMATION_THETA_20DEG_YAW_M200DEG = 5
ARDRONE_ANIMATION_TURNAROUND = 6
ARDRONE_ANIMATION_TURNAROUND_GODOWN = 7
ARDRONE_ANIMATION_YAW_SHAKE = 8